version: '3'
services:
  front:
    image: front-poly-esprit:e1
    build:
      context: ../front-end
      dockerfile: ../front-end/Dockerfile
      args:
        ENVIRONMENT: proxy
#        PROXYURL: "http:\\/\\/proxy.polyquiz.com:8888\\/back"
        DOMAIN: "proxy.polyQuiz.com"
    user: nginx
    depends_on:
      back:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
  back:
    image: back-poly-esprit:e1
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    user: node
    volumes:
      - back-storage:/home/node/database
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9428/api/status || exit 1" ]
      interval: 10s
      timeout: 10s
      start_period: 5s
      retries: 5
  proxy:
    image: proxy-poly-esprit:e4
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8888:80
    depends_on:
      - front
      - back
volumes:
  back-storage: